// Fonts
import { Geist, Geist_Mono } from "next/font/google";

// Global Components
import Announcement from "./components/announcement bar/announcement";
import Navbar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";

// CSS
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Announcement />
        <Navbar />
        <main className="main">{children}</main>
        <Footer />
        </body>
    </html>
  );
}
